public class ExamMessageConstants {
    public static final String CDFA_EXAM_RESULT_EMAIL_SUBJECT = System.Label.CDFA_EXAM_Result_Email_Subject; 
	public static final String EXAMINATION_SCORE_STRING = 'Examination Score';
    public static final String EXAMINATION_SCORE_PERCENTAGE = '%';
    
    public static final Double MIN_MARKS_REQUIRED = 70;
    public static final String EXAMINATION_TYPE_STRING = 'Examination Type';
    
    public static final String EXAMINATION_SERVICE_AGENT_LICENSE_NUMBER = 'Service Agent License Number';
    
    public static final String EXAM_TYPE_RENEW = 'Renewal';
    public static final String EXAM_TYPE_NEW = 'New';
    
    
    public static final String CONTACT_FIRST_NAME = 'Contact First Name';
    public static final String CONTACT_MIDDLE_NAME = 'Contact Middle Name';
	public static final String CONTACT_LAST_NAME = 'Contact Last Name';
    public static final String CONTACT_ADDRESS_LINE_1 = 'Contact Address Line 1';
    public static final String CONTACT_ADDRESS_CITY = 'Contact Address City';
    public static final String CONTACT_ADDRESS_STATE = 'Contact Address State';
    public static final String CONTACT_ADDRESS_ZIP_CODE = 'Contact Address ZIP Code';
    public static final String CONTACT_PHONE_NUMBER = 'Contact Phone Number';
    public static final String CONTACT_EMAIL_ADDRESS = 'Contact Email Address';
    
    public static final String PROOF_OF_IDENTITY_TYPE = 'Proof of Identity Type';
    public static final String PROOF_OF_IDENTITY_NUMBER = 'Proof of Identity Number';
    
    public static final String EXAMINATION_DATE = 'Examination Date';
    
    public static final String TASK_SUBJECT = 'Exam Result Review';
    
}